### ISSUE TITLE
Add UUID Fix

### ISSUE THREAD

**Issue by Moe23333** [Satxm/mcwifipnp#16]
Add an option that allows to use UUID in offline mode to prevents the loss of inventory contents when switching from online mode to offline mode, just like the [LAN Server Properties](https://github.com/rikka0w0/LanServerProperties) mod.

**Comment by Satxm** [comment]
I will try this.

**Comment by rikka0w0** [comment]
作者还在不，我是LAN Server Properties作者，考虑合作不，我看你这边完成度挺高了，我那边有点做不动了QAQ

**Comment by Satxm** [comment]
好啊，期待合作！

**Comment by rikka0w0** [comment]
想了想，我感觉UUID Fix这个功能适合做成单独的模组，因为我发现专用服务器偶尔也会用到

可以加我qq细聊QwQ

**Comment by rikka0w0** [comment]
思考了一下，可以在提供当前功能的情况下把这个mod做成一个插件平台。
这里做成滚动的列表
![image](https://github.com/user-attachments/assets/e812c970-b168-4ac8-953e-fa3d4f9a677c)
然后插件可以注册按钮和文本框之类的。

插件可以是：
1. UUID修复
2. Sakura FRP一键开服
3. Cloudflare Tunnel一键开服

**Comment by Satxm** [comment]
我这段时间参考您的代码添加了 UUID 修复功能，一键开服需要第三方软件，需要慢慢研究

**Comment by Pival81** [comment]
could you please add the ability to use the UUID fix mode on dedicated servers as well?
