### ISSUE TITLE
FancyMenu模组无法移动“对局域网开放”按钮

### ISSUE THREAD

**Issue by ghost** [Satxm/mcwifipnp#2]

**Comment by Satxm** [comment]
我无法修复这个问题，FancyMenu模组可能未添加对由Forge api添加进去的按钮的修改。

**Comment by Satxm** [comment]
此问题现在应该已经修复。稍后我会上传文件。在1.4.6版本里，按钮大小使用原版定义的大小和位置，现在应该可以移动了

**Comment by Satxm** [comment]
![2021-08-22_085401](https://user-images.githubusercontent.com/56530136/130338577-f21ca99f-b5b1-4c64-bb3d-838ff8170b75.png)
![2021-08-22_085307](https://user-images.githubusercontent.com/56530136/130338580-7a686830-a6a9-4b67-a5eb-48250e9c2432.png)

**Comment by ghost** [comment]
哦！谢了！
