### ISSUE TITLE
1.19.2 - Startup Failure Due to ``Forge Mod Loader Language`` Error

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Satxm/mcwifipnp#20]
Latest Log https://gist.github.com/P3rf3ctXZer0/db9d4c63e7db291dddf3ee36c89f9e77
Crash Log https://gist.github.com/P3rf3ctXZer0/054960546deb89c1a2acc6a8d0755f5e
Forge Version 43.2.6

**Comment by Satxm** [comment]
In my test, my mod runs fine.
