### ISSUE TITLE
Missing English translations for some tooltip information

### ISSUE THREAD

**Issue by bwilliance** [Satxm/mcwifipnp#25]
Most of the tooltips that appear when hovering over the buttons aren't translated to English. I've created a resource pack that sort of fixes this, and adds a bit more info to the tooltips. Translations might not be fully accurate, though.

[mcwifipnp missing english translations.zip](https://github.com/Satxm/mcwifipnp/files/12297812/mcwifipnp.missing.english.translations.zip)

**Comment by Satxm** [comment]
Will update in next upload.
