### ISSUE TITLE
Game Menu Mod Option模组使该模组失效

### ISSUE THREAD

**Issue by ghost** [Satxm/mcwifipnp#3]
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption
这俩模组装一起后，“对局域网开放”页面回归原版

**Comment by Satxm** [comment]
你应该在他那里报告一下这个问题，我没有办法修复。

**Comment by Satxm** [comment]
或者使用其他mod来添加forge的模组设置

**Comment by ghost** [comment]
ok，我去康康

**Comment by Satxm** [comment]
或者我给你写一个

**Comment by ghost** [comment]
？？？！
那可真是太感激不尽了！

**Comment by Satxm** [comment]
![2021-08-23_154040](https://user-images.githubusercontent.com/56530136/130409276-b7ee6d36-19af-4641-8c15-55e6609dbb48.jpg)
吧报告bug的按钮换掉了

**Comment by ghost** [comment]
我们没有bug，这些都是特性（）

**Comment by Satxm** [comment]
好像两个一起用会冲突，我想想解决办法

**Comment by Satxm** [comment]
刚才写错行了，emm
我上传上来，你解压并替换掉原来文件
[mcwifipnp-1.4.6-1.16.5-forge.jar.zip](https://github.com/Satxm/mcwifipnp/files/7030198/mcwifipnp-1.4.6-1.16.5-forge.jar.zip)

**Comment by ghost** [comment]
哦好

**Comment by ghost** [comment]
其实你可以将它分离出来做成另一个mod的
