### ISSUE TITLE
i cannot seem to get the mod to work (1.18.2)

### ISSUE THREAD

**Issue by Kleptoplasm** [Satxm/mcwifipnp#30]
It says in the game chat that it is unable to forward the port.

**Comment by Satxm** [comment]
Your network environment doesn't support UPnP , so unable to forward the port. Y can use 3rd software to mapping port.

**Comment by Satxm** [comment]
Your network environment doesn't support UPnP , so unable to forward the port. Y can use 3rd software to mapping port.
