### ISSUE TITLE
无法转发端口xxxxx：路由器上未启用UPnP，你可能需要端口映射软件。

### ISSUE THREAD

**Issue by ghost** [Satxm/mcwifipnp#31]
出现了这个提示是不是就意味着只能自己手动搭建端口映射去联机了？
网络连接的是学校的校园网，不知道是不是因为校园网导致的该问题。

**Comment by Satxm** [comment]
是的，这种情况你所用网络upnp不可用，请使用第三方端口转发软件。大部分校园网这个应该都是禁用的
