### ISSUE TITLE
Issues when used with No Report Button mod

### ISSUE THREAD

**Issue by bwilliance** [Satxm/mcwifipnp#32]
On the latest version of mcwifipnp (1.6.8), the Open To LAN button has issues when paired with the No Report Button mod.
Link to the mod: https://modrinth.com/mod/nrb

When both mods are present, on singleplayer, the Open To LAN button is able to be clicked even after starting a LAN world.

![2024-01-21_18 30 13](https://github.com/Satxm/mcwifipnp/assets/97874863/0f2efe85-108c-40be-8da2-7e02eb925026)
![2024-01-21_18 29 49](https://github.com/Satxm/mcwifipnp/assets/97874863/19f32d2d-6083-49ae-8e73-f705701a388c)

On multiplayer, the LAN button is able to be clicked (this would normally be grayed out by NRB mod).

![2024-01-21_18 32 24](https://github.com/Satxm/mcwifipnp/assets/97874863/30ce6c77-f106-496b-a2d4-39bafdcea546)

Clicking it on multiplayer will cause the game to crash and show this error on the Minecraft Launcher:

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_27050(net.minecraft.class_5218)" because "server" is null

Exit Code: -1

Crash report: [crash-2024-01-21_18.34.47-client.txt](https://github.com/Satxm/mcwifipnp/files/14004045/crash-2024-01-21_18.34.47-client.txt)

There seems to be no issues with this in the previous version of mcwifipnp.

**Comment by Satxm** [comment]
Fixd in 1.6.9, I added new a button, but not apply old button‘s active status to the new, in 1.6.9 all changed.
![2024-01-22_230658](https://github.com/Satxm/mcwifipnp/assets/56530136/5e8ec27a-8680-45a2-a19d-a910d788f507)
In this picture, I add No Report Button mod, open to lan Button will disable when started lan word or joind a server.
