### ISSUE TITLE
Other player shows up with basic skin/其他玩家以基础皮肤出现

### ISSUE THREAD

**Issue by Official-V-Zer0** [Satxm/mcwifipnp#37]
So a friend of mine joined the server with the global ipv4 copy, it worked but the issue iss that they had changed their mc username, so they appeared with their old username and the basic Alex skin, so I wonder if this is a fixable issue or something you are aware of.

and seeing as you're chinese I will now proceed to use google translate to translate this as I'm not chinese.

用谷歌翻译翻译

因此，我的一个朋友使用全局 ipv4 副本加入了服务器，它可以工作，但问题是他们更改了 mc 用户名，因此他们以旧用户名和基本 Alex 皮肤出现，所以我想知道这是否是一个可修复的问题或您知道的事情。

**Comment by Satxm** [comment]
You can use CustomSkinLoader mod to load player skins.

**Comment by Official-V-Zer0** [comment]
That seems too complicated to try and do for such a problem that I have commonly seen somehow just fix itself and it's not a major problem currently. And also now the lan plug-n-play mod says I need a better version of Java (21 or better), when I have Java 22 (but it only registers java 17 for some reason).

对于我经常看到的这样一个问题，这似乎太复杂了，无法自行解决，而且目前这不是一个主要问题。而且现在 lan 即插即用 mod 说我需要一个更好版本的 Java（21 或更好），当我有 Java 22 时（但由于某种原因它只注册 java 17）。

**Comment by Satxm** [comment]
> That seems too complicated to try and do for such a problem that I have commonly seen somehow just fix itself and it's not a major problem currently. And also now the lan plug-n-play mod says I need a better version of Java (21 or better), when I have Java 22 (but it only registers java 17 for some reason).
> 
> 对于我经常看到的这样一个问题，这似乎太复杂了，无法自行解决，而且目前这不是一个主要问题。而且现在 lan 即插即用 mod 说我需要一个更好版本的 Java（21 或更好），当我有 Java 22 时（但由于某种原因它只注册 java 17）。

I have made adjustents of `1.7.1-1.20.6-fabric`.
![2024-08-15_165453](https://github.com/user-attachments/assets/52029fe8-1e85-4fa3-aabd-911176f40c6b)

`1.7.1-1.20.4-fabric` can be run with Java and MC 1.20.6.
