### ISSUE TITLE
open jdk 版本問題

### ISSUE THREAD

**Issue by kevin930321** [Satxm/mcwifipnp#38]
模組 'LAN World Plug-n-Play' (mcwifipnp) 1.7.1 需要 版本 21 以上（含） 'OpenJDK 64-Bit Server VM' (java)，但只有錯誤的版本可用：17！

**Comment by Satxm** [comment]
mc版本是多少？

从1.17（21w19a）开始，运行Minecraft的最低要求是Java 16。
从1.18（1.18-pre2）开始，运行Minecraft的最低要求是Java 17。
从1.20.5（24w14a）开始，运行Minecraft的最低要求是Java 21，且操作系统要求为64位。

**Comment by kevin930321** [comment]
1.20.4

**Comment by Satxm** [comment]
你下载安装1.7.1-1.20.4版本

**Comment by Satxm** [comment]
已经调整`1.7.1-1.20.6-fabric`的版本对于关系。
![2024-08-15_165453](https://github.com/user-attachments/assets/52029fe8-1e85-4fa3-aabd-911176f40c6b)

`1.7.1-1.20.4-fabric` can be run with Java and MC 1.20.6.
