### ISSUE TITLE
1.7.1 fabric variant, 1.20.4 and 1.20.6 released, issues with support versions

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Satxm/mcwifipnp#39]
Both `1.7.1-1.20.4-fabric` and `1.7.1-1.20.6-fabric` are marked as supporting `1.20.4–1.20.6` on Modrinth.

This is a bit confusing. Some launcher developers with the ability to download mods have received feedback related to this.

I noticed that the 1.20.6 release requires Java ≥ 21, and if someone downloads the 1.20.6 release on a 1.20.4 instance and launches the game with Java 17, there will be errors with the Fabric Loader.

Could you please make some adjustments to the release on Modrinth? Regards.

**Comment by Satxm** [comment]
I have made adjustents of `1.7.1-1.20.6-fabric`.
![2024-08-15_165453](https://github.com/user-attachments/assets/52029fe8-1e85-4fa3-aabd-911176f40c6b)

`1.7.1-1.20.4-fabric` can be run with Java and MC 1.20.6.
