### ISSUE TITLE
Feature Suggestion: Configurable Player Limit

### ISSUE THREAD

**Issue by Siuolplex** [Satxm/mcwifipnp#4]
Heya! I was wondering if there could be a configurable player limit added?

**Comment by Satxm** [comment]
I am trying to add whitelist, but it seams hard for client, I am still working with it.

**Comment by Siuolplex** [comment]
Alright then.

**Comment by Felix14-v2** [comment]
[Custom LAN](https://github.com/DimiDimit/Custom-LAN) contains this functionality, maybe it will help you.

**Comment by Satxm** [comment]
Max player limit was added.
Whitelist still not working.
