### ISSUE TITLE
What ip do i have to send??

### ISSUE THREAD

**Issue by Alb654-hue** [Satxm/mcwifipnp#44]
Hey 👋🏻 I have a question what ip should I send to my friends there's bunch of ip's like ipv4 ipv6 ipv6 global pls help me I want to play with my friend pls

**Comment by Satxm** [comment]
You should send that ip display with global, If this ip your friends can not connected, you can use port mapping software.

**Comment by Alb654-hue** [comment]
> You should send that ip display with global, If this ip your friends can not connected, you can use port mapping software.

What is port mapping software?? Pls explain

**Comment by Satxm** [comment]
Such as frp nps ZeroTier or proxy software etc.  In general the ip display with global can be connected.

**Comment by Alb654-hue** [comment]
I have not port forward my router will it work??
