### ISSUE TITLE
UPNP for Simple Voice Chat mod

### ISSUE THREAD

**Issue by Lukebb04** [Satxm/mcwifipnp#6]
UPNP for [Simple Voice Chat](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat) so you can use voice chat (Port: 24454)

**Comment by Satxm** [comment]
Please add description.

**Comment by Lukebb04** [comment]
Done

**Comment by Satxm** [comment]
UPHP ? or UPNP ?
Simple Voice Chat mod isn't my mod. You may should add issue in Simple Voice Chat mod.

**Comment by Lukebb04** [comment]
UPNP

**Comment by Satxm** [comment]
Should I add some function into my mod? Please give me a clear description.

**Comment by Lukebb04** [comment]
That what i'm asking, I think if it detects that the mod is installed it adds that option the menu

**Comment by Satxm** [comment]
No, That shouldn't my job. You can add isuss in [Simple Voice Chat](https://github.com/henkelmax/simple-voice-chat/issues) mod's github.
Simple Voice Chat mod starts voicechat server after Integrated Server started, and it use redom port, not Port: 24454. 
![2022-01-09_185610](https://user-images.githubusercontent.com/56530136/148679939-294c010f-f2c1-400f-9395-3afedceb0f69.png)
![2022-01-09_185642](https://user-images.githubusercontent.com/56530136/148679942-0215a287-a6fe-47e1-8563-c6c531a0923a.png)
And than another player join server, the voicechat auto connected.
![2022-01-09_191853](https://user-images.githubusercontent.com/56530136/148680072-715c5618-251d-46f8-b060-16e95dd73ed0.png)
![2022-01-09_191922](https://user-images.githubusercontent.com/56530136/148680080-9dab9aaf-b443-491a-a4a9-842d89bea05d.png)

If you need UPNP, you should add issues in Simple Voice Chat, let them add this function.
