### ISSUE TITLE
Stops working after Save-and-quit.

### ISSUE THREAD

**Issue by Hail99wasd** [Satxm/mcwifipnp#7]
Title. Using forge version. Players can't join after I start the world up again (and open to lan) after having quit out of it.

**Comment by Satxm** [comment]
Please upload log and your mod list or your mods folder.

**Comment by Hail99wasd** [comment]
Only mod is your mod. But here's the log.
[latest.log](https://github.com/Satxm/mcwifipnp/files/7937728/latest.log)

**Comment by Satxm** [comment]
Can you upload your friends log.

**Comment by Satxm** [comment]
I can't reproduce the problem, can you upload your friend's logs.
