### ISSUE TITLE
Add /OP /DEOP commands

### ISSUE THREAD

**Issue by SeasonPhan** [Satxm/mcwifipnp#8]
I think  everyone should not have permission to use the commands with "allow cheat: on"

**Comment by dogeeuser** [comment]
use this mod to add /op /deop
https://modrinth.com/mod/lan-operators

**Comment by P3rf3ctXZer0** [comment]
I need a similar to this but for forge! Also I need it for 1.19.2.

**Comment by Satxm** [comment]
Added in 1.59, pls update.
